paths:
  input: ./input/smiling_2.mov
  input2: ./input/amuse.png
  output: ./output/SN003_dense.mp4

params:
  animate: 1
  type: video
  img_size: 512
  vid_interval: 5
  img_interval: 300
  save_flg: 1